---
- name: Create a user and add to sudo group
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Create a new user
      user:
        name: your_username
        password: "{{ vault_password | password_hash('sha512') }}"
        groups: sudo
        state: present

    - name: Ensure the sudo group is present
      group:
        name: sudo
        state: present

