- name: Ensure /etc/aliases contains the correct root alias
  hosts: all
  tasks:
    - name: Ensure root is aliased to darryl.payton@gmail.com
      lineinfile:
        path: /etc/aliases
        regexp: '^root:'
        line: 'root: darryl.payton@gmail.com'
        create: yes
      become: yes
- name: Manage Postfix configuration
  hosts: all
  become: yes
  tasks:
    - name: Backup existing main.cf file
      copy:
        src: /etc/postfix/main.cf
        dest: /etc/postfix/main.cf.old
        remote_src: yes
      ignore_errors: yes

    - name: Create new main.cf file with specified content
      copy:
        dest: /etc/postfix/main.cf
        content: |
          myhostname = mm-test.dabububu.com
          alias_maps = hash:/etc/aliases
          alias_database = hash:/etc/aliases
          mydestination = $myhostname, mm-test, localhost.localdomain, , localhost
          relayhost = test.smtp.com
          mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
          mailbox_size_limit = 0
          recipient_delimiter = +
          inet_interfaces = all
          inet_protocols = all

    - name: Restart Postfix to apply changes
      service:
        name: postfix
        state: restarted
