---
- name: Install and configure SNMPv3 for SolarWinds on Ubuntu (UFW locked down)
  hosts: evrs
  become: true
  vars:
    # Defaults / optional
    snmp_location: "Unknown Location"   # override per-host in inventory
    snmp_contact: "noc@example.com"     # override via Semaphore if desired
    configure_ufw: true
    snmpv3_auth_protocol: "SHA"
    snmpv3_priv_protocol: "AES"

  tasks:
    - name: Fail if required vars are missing
      ansible.builtin.assert:
        that:
          - solarwinds_server_ip is defined
          - snmpv3_username is defined
          - snmpv3_auth_password is defined
          - snmpv3_priv_password is defined
        fail_msg: >
          Missing required variables. Provide solarwinds_server_ip, snmpv3_username,
          snmpv3_auth_password, snmpv3_priv_password (Semaphore Variables recommended).

    - name: Install SNMP packages and dependencies
      ansible.builtin.apt:
        name:
          - snmp
          - snmpd
          - ufw
          - libsnmp-dev  # This was the missing package
        state: present
        update_cache: yes

    - name: Ensure snmpd is stopped before user creation
      ansible.builtin.systemd:
        name: snmpd
        state: stopped

    - name: Configure /etc/snmp/snmpd.conf (SNMPv3 only)
      ansible.builtin.copy:
        dest: /etc/snmp/snmpd.conf
        owner: root
        group: root
        mode: "0644"
        content: |
          # [ SNMPD configuration content from your original playbook... ]
          agentAddress udp:161
          sysLocation {{ snmp_location }}
          sysContact  {{ snmp_contact }}
          view   systemonly  included   .1.3.6.1.2.1.1
          view   systemonly  included   .1.3.6.1.2.1.25.1
          rouser {{ snmpv3_username }} authPriv -V systemonly
          dontLogTCPWrappersConnects yes

    - name: Check if SNMPv3 user already exists
      ansible.builtin.command:
        cmd: grep -c "usmUser.*{{ snmpv3_username }}" /var/lib/snmp/snmpd.conf
      register: snmpv3_user_count
      changed_when: false
      failed_when: false

    - name: Create SNMPv3 user (read-only, authPriv)
      ansible.builtin.command:
        argv:
          - /usr/bin/net-snmp-create-v3-user
          - -ro
          - -a
          - "{{ snmpv3_auth_protocol }}"
          - -A
          - "{{ snmpv3_auth_password }}"
          - -x
          - "{{ snmpv3_priv_protocol }}"
          - -X
          - "{{ snmpv3_priv_password }}"
          - "{{ snmpv3_username }}"
      when: snmpv3_user_count.stdout is not defined or snmpv3_user_count.stdout | int == 0

    - name: Ensure snmpd is enabled and running
      ansible.builtin.systemd:
        name: snmpd
        enabled: true
        state: restarted

    # -------------------------
    # UFW lock down to SolarWinds
    # -------------------------
    - name: Ensure UFW is enabled
      ansible.builtin.ufw:
        state: enabled
      when: configure_ufw | bool

    - name: Allow SNMP (UDP/161) only from SolarWinds server
      ansible.builtin.ufw:
        rule: allow
        proto: udp
        port: "161"
        from_ip: "{{ solarwinds_server_ip }}"
      when: configure_ufw | bool

    - name: Deny SNMP (UDP/161) from everywhere else
      ansible.builtin.ufw:
        rule: deny
        proto: udp
        port: "161"
      when: configure_ufw | bool
