---
- name: Check ping and sudo access
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check host connectivity
      ping:

    - name: Run apt update using command
      command: apt update
      register: apt_output
      changed_when: false

    - name: Show apt update output
      debug:
        var: apt_output.stdout_lines
