---
- name: Check ping and sudo access
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check host connectivity
      ansible.builtin.ping:

    - name: Run apt update with command module (fixed syntax)
      ansible.builtin.command: apt update
      register: apt_output
      changed_when: false

    - name: Show apt output
      ansible.builtin.debug:
        var: apt_output.stdout_lines
