- name: Update and upgrade all packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove obsolete packages
      apt:
        autoremove: yes
