---
- name: Check password expiration for all users in the sudo group
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get list of users in the sudo group
      shell: |
        getent group sudo | awk -F: '{print $4}' | tr ',' '\n' | sort | uniq | grep -v '^$'
      register: sudo_users

    - name: Check password expiration for each sudo user
      shell: chage -l {{ item }}
      loop: "{{ sudo_users.stdout_lines }}"
      register: chage_results

    - name: Print password expiration for each sudo user
      debug:
        msg: |
          User: {{ item.item }}
          Password Info:
          {{ item.stdout }}
      loop: "{{ chage_results.results }}"
