- name: Check password expirations for /home users and notify
  hosts: all
  become: yes
  vars:
    smtp_host: relay.internal.company       # Replace with your SMTP relay
    smtp_port: 25
    email_to: security-team@yourcompany.com # Replace with your recipient
    email_from: ansible@yourcompany.com     # Replace with your sender
    today: "{{ lookup('pipe', 'date +%Y-%m-%d') | to_datetime('%Y-%m-%d') }}"

  tasks:
    - name: Get usernames from /home
      shell: "ls -1 /home"
      register: home_users
      changed_when: false

    - name: Initialize list for expiring accounts
      set_fact:
        expiring_accounts: []

    - name: Check password expiration for each user
      command: "chage -l {{ item }}"
      register: chage_output
      loop: "{{ home_users.stdout_lines }}"
      failed_when: false
      changed_when: false

    - name: Extract raw expiry line and value
      set_fact:
        expiry_line_raw: "{{ item.stdout_lines | select('search', '^Password expires') | first | default('') }}"
        expiry_value: >-
          {{
            (':' in expiry_line_raw)
              | ternary(expiry_line_raw.split(':', 1)[1] | regex_replace('\\s+', ' ') | trim, '')
          }}
        expiry_valid: "{{ expiry_value != '' and expiry_value != 'never' }}"
        current_username: "{{ item.item }}"
      loop: "{{ chage_output.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Set expiry_date only if valid
      set_fact:
        expiry_date: "{{ expiry_value | to_datetime('%b %d, %Y') }}"
      when: expiry_valid

    - name: Calculate days remaining if valid
      set_fact:
        days_remaining: "{{ (expiry_date - today).days | int }}"
      when: expiry_valid

    - name: Default days remaining if not valid
      set_fact:
        days_remaining: -999
      when: not expiry_valid

    - name: Append user to expiring_accounts if within threshold
      set_fact:
        expiring_accounts: "{{ expiring_accounts + [user_entry] }}"
      vars:
        user_entry: >-
          {{
            (expiry_valid and (days_remaining <= 15))
              | ternary({
                'username': current_username,
                'days_remaining': days_remaining,
                'expiry_date': expiry_date
              }, omit)
          }}
      when: expiry_valid

    - name: Send email if any accounts are expiring
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "⚠️ Expiring Passwords on {{ ansible_hostname }}"
        body: |
          The following user accounts on {{ ansible_hostname }} have expired or are expiring soon:

          {% for acct in expiring_accounts %}
          - {{ acct.username }}: expires {{ acct.expiry_date.strftime('%Y-%m-%d') if acct.expiry_date is not none else 'unknown' }}, in {{ acct.days_remaining }} day(s)
          {% endfor %}

          Please rotate these passwords to avoid account lockouts.
        secure: never
      when: expiring_accounts | length > 0
