---
- name: Gather sudo password expiry info from all hosts
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Get sudo group entry using getent module
      ansible.builtin.getent:
        database: group
        key: sudo
      register: sudo_group

    - name: Extract list of sudo users
      set_fact:
        sudo_users: "{{ (sudo_group['ansible_facts']['getent_group']['sudo'][2].split(',')) if (sudo_group['ansible_facts']['getent_group']['sudo']|length > 2 and sudo_group['ansible_facts']['getent_group']['sudo'][2] != '') else [] }}"

    - name: Get password expiration date (ISO format) for each sudo user
      shell: |
        exp=$(chage -l {{ item }} | awk -F: '/Password expires/ {print $2}' | xargs)
        if [ "$exp" = "never" ] || [ -z "$exp" ]; then
          echo "never"
        else
          date -d "$exp" +%Y-%m-%d
        fi
      loop: "{{ sudo_users }}"
      register: chage_results
      changed_when: false

    - name: Build sudo expiry results for this host
      set_fact:
        sudo_expiry_results: >-
          {{
            sudo_users | zip(chage_results.results | map(attribute='stdout') | list) | map('list') | map('join', ',') | list
          }}

- name: Send consolidated email with all hosts' sudo user expiry info
  hosts: localhost
  gather_facts: no
  vars:
    mail_to: "usafea6.evrs.support@us.af.mil"
    mail_from: "noreply@us.af.mil"
    mail_subject: "All Hosts Sudo Users Report"
    smtp_host: "af-smtp.us.af.mil"
    smtp_port: 25
  tasks:
    - name: Build email body from all hosts
      set_fact:
        mail_body: |-
          Hostname,Username,Password Expires
          {%- for host in groups['all'] %}
            {%- if hostvars[host]['sudo_expiry_results'] is defined %}
              {%- for line in hostvars[host]['sudo_expiry_results'] %}
                {{ host }},{{ line }}
              {%- endfor %}
            {%- endif %}
          {%- endfor %}

    - name: Send results email via SMTP relay
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "{{ mail_subject }}"
        body: "{{ mail_body }}"
        subtype: plain
