- name: Check password expirations for /home users and notify
  hosts: all
  become: yes
  vars:
    smtp_host: af-smtp.us.af.mil
    smtp_port: 25
    email_to: usafea6.evrs.support@us.af.mil
    email_from: noreply@us.af.mil
    today: "{{ lookup('pipe', 'date +%Y-%m-%d') | to_datetime('%Y-%m-%d') }}"

  tasks:
    - name: Get usernames from /home
      shell: "ls -1 /home"
      register: home_users
      changed_when: false

    - name: Check password expiration for each user and collect results
      vars:
        expiry_line_raw: "{{ item.stdout_lines | select('search', '^Password expires') | first | default('') }}"
        expiry_value: >-
          {{
            (':' in expiry_line_raw)
              | ternary(expiry_line_raw.split(':', 1)[1] | regex_replace('\\s+', ' ') | trim, '')
          }}
        expiry_valid: "{{ expiry_value != '' and expiry_value != 'never' }}"
        expiry_date: >-
          {{ expiry_value | to_datetime('%b %d, %Y') if expiry_valid else none }}
        days_remaining: >-
          {{ (expiry_date - today).days if expiry_valid else -999 }}
      set_fact:
        password_results: "{{ password_results | default([]) + [ {
          'username': item.item,
          'expiry_valid': expiry_valid,
          'expiry_date': expiry_date,
          'days_remaining': days_remaining
        } ] }}"
      loop: "{{ chage_output.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: item.stdout_lines is defined

    - name: Collect expiring accounts (expired or expiring within 15 days)
      set_fact:
        expiring_accounts: >-
          {{ password_results
               | selectattr('expiry_valid', 'equalto', true)
               | selectattr('days_remaining', 'le', 15)
               | list
          }}

    - name: Send email if any accounts are expiring
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "⚠️ Expiring Passwords on {{ ansible_hostname }}"
        body: |
          The following user accounts on {{ ansible_hostname }} have expired or are expiring soon:

          {% for acct in expiring_accounts %}
          - {{ acct.username }}: expires {{ acct.expiry_date.strftime('%Y-%m-%d') if acct.expiry_date is not none else 'unknown' }}, in {{ acct.days_remaining }} day(s)
          {% endfor %}

          Please rotate these passwords to avoid account lockouts.
        secure: never
      when: expiring_accounts | length > 0
