---
- name: Check password expiration date for all users in the sudo group
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get sudo group entry using getent lookup
      getent:
        database: group 
        key: sudo
      register: sudo_group
      failed_when: sudo_group.rc != 0
