- name: Check password expirations for /home users and notify
  hosts: all
  become: yes
  vars:
    smtp_host: relay.internal.company     # Replace with your SMTP relay
    smtp_port: 25
    email_to: security-team@yourcompany.com
    email_from: ansible@yourcompany.com

  tasks:
    - name: Get usernames from /home
      shell: "ls -1 /home"
      register: home_users
      changed_when: false

    - name: Initialize list for expiring accounts
      set_fact:
        expiring_accounts: []

    - name: Check password expiration for each user
      command: "chage -l {{ item }}"
      register: chage_output
      loop: "{{ home_users.stdout_lines }}"
      failed_when: false
      changed_when: false

    - name: Process expiration info
      set_fact:
        expiring_accounts: "{{ expiring_accounts + [user_entry] }}"
      vars:
        expiry_line_raw: "{{ item.stdout_lines | select('search', '^Password expires') | first | default('') }}"
        expiry_value: "{{ expiry_line_raw.split(':', 1)[1] | trim }}"
        today_str: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
        today: "{{ today_str | to_datetime('%Y-%m-%d') }}"
        expiry_valid: "{{ expiry_value != '' and expiry_value != 'never' }}"
        expiry_date: "{{ expiry_valid | ternary(expiry_value | to_datetime('%b %d, %Y'), none) }}"
        days_remaining: "{{ expiry_date is not none | ternary((expiry_date - today).days, -999) }}"
        user_entry: >-
          {{
            (expiry_valid and (days_remaining | int <= 15))
              | ternary({
                'username': item.item,
                'days_remaining': days_remaining | int,
                'expiry_date': expiry_date
              }, omit)
          }}
      loop: "{{ chage_output.results }}"
      when: item.stdout is defined and 'Password expires' in item.stdout

    - name: Send email if any accounts are expiring
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "⚠️ Expiring Passwords on {{ ansible_hostname }}"
        body: |
          The following user accounts on {{ ansible_hostname }} have expired or are expiring soon:

          {% for acct in expiring_accounts %}
          - {{ acct.username }}: expires {{ acct.expiry_date.strftime('%Y-%m-%d') }}, in {{ acct.days_remaining }} day(s)
          {% endfor %}

          Please rotate these passwords to avoid account lockouts.
        secure: never
      when: expiring_accounts | length > 0
